using System.Collections.Generic;
using UnityEngine;
using CUESDK;

public static class KeyMapping {
    private static Dictionary<KeyCode, CorsairLedId> keyCodeLedIdMapping;

    static KeyMapping() {
        keyCodeLedIdMapping = new Dictionary<KeyCode, CorsairLedId> {
            { KeyCode.A, CorsairLedId.KeyboardA },
            { KeyCode.B, CorsairLedId.KeyboardB },
            { KeyCode.C, CorsairLedId.KeyboardC },
            { KeyCode.D, CorsairLedId.KeyboardD },
            { KeyCode.E, CorsairLedId.KeyboardE },
            { KeyCode.F, CorsairLedId.KeyboardF },
            { KeyCode.G, CorsairLedId.KeyboardG },
            { KeyCode.H, CorsairLedId.KeyboardH },
            { KeyCode.I, CorsairLedId.KeyboardI },
            { KeyCode.J, CorsairLedId.KeyboardJ },
            { KeyCode.K, CorsairLedId.KeyboardK },
            { KeyCode.L, CorsairLedId.KeyboardL },
            { KeyCode.M, CorsairLedId.KeyboardM },
            { KeyCode.N, CorsairLedId.KeyboardN },
            { KeyCode.O, CorsairLedId.KeyboardO },
            { KeyCode.P, CorsairLedId.KeyboardP },
            { KeyCode.Q, CorsairLedId.KeyboardQ },
            { KeyCode.R, CorsairLedId.KeyboardR },
            { KeyCode.S, CorsairLedId.KeyboardS },
            { KeyCode.T, CorsairLedId.KeyboardT },
            { KeyCode.U, CorsairLedId.KeyboardU },
            { KeyCode.V, CorsairLedId.KeyboardV },
            { KeyCode.W, CorsairLedId.KeyboardW },
            { KeyCode.X, CorsairLedId.KeyboardX },
            { KeyCode.Y, CorsairLedId.KeyboardY },
            { KeyCode.Z, CorsairLedId.KeyboardZ },
            { KeyCode.Alpha0, CorsairLedId.Keyboard0 },
            { KeyCode.Alpha1, CorsairLedId.Keyboard1 },
            { KeyCode.Alpha2, CorsairLedId.Keyboard2 },
            { KeyCode.Alpha3, CorsairLedId.Keyboard3 },
            { KeyCode.Alpha4, CorsairLedId.Keyboard4 },
            { KeyCode.Alpha5, CorsairLedId.Keyboard5 },
            { KeyCode.Alpha6, CorsairLedId.Keyboard6 },
            { KeyCode.Alpha7, CorsairLedId.Keyboard7 },
            { KeyCode.Alpha8, CorsairLedId.Keyboard8 },
            { KeyCode.Alpha9, CorsairLedId.Keyboard9 },
            { KeyCode.Space, CorsairLedId.KeyboardSpace },
            { KeyCode.LeftShift, CorsairLedId.KeyboardLeftShift },
            { KeyCode.RightShift, CorsairLedId.KeyboardRightShift },
            { KeyCode.LeftControl, CorsairLedId.KeyboardLeftCtrl },
            { KeyCode.RightControl, CorsairLedId.KeyboardRightCtrl },
            { KeyCode.LeftAlt, CorsairLedId.KeyboardLeftAlt },
            { KeyCode.RightAlt, CorsairLedId.KeyboardRightAlt },
            { KeyCode.LeftCommand, CorsairLedId.KeyboardLeftGui },
            { KeyCode.RightCommand, CorsairLedId.KeyboardRightGui },
            { KeyCode.LeftArrow, CorsairLedId.KeyboardLeftArrow },
            { KeyCode.RightArrow, CorsairLedId.KeyboardRightArrow },
            { KeyCode.UpArrow, CorsairLedId.KeyboardUpArrow },
            { KeyCode.DownArrow, CorsairLedId.KeyboardDownArrow },
            { KeyCode.Escape, CorsairLedId.KeyboardEscape },
            { KeyCode.Return, CorsairLedId.KeyboardEnter },
            { KeyCode.Backspace, CorsairLedId.KeyboardBackspace },
            { KeyCode.Tab, CorsairLedId.KeyboardTab },
            { KeyCode.CapsLock, CorsairLedId.KeyboardCapsLock },
            { KeyCode.F1, CorsairLedId.KeyboardF1 },
            { KeyCode.F2, CorsairLedId.KeyboardF2 },
            { KeyCode.F3, CorsairLedId.KeyboardF3 },
            { KeyCode.F4, CorsairLedId.KeyboardF4 },
            { KeyCode.F5, CorsairLedId.KeyboardF5 },
            { KeyCode.F6, CorsairLedId.KeyboardF6 },
            { KeyCode.F7, CorsairLedId.KeyboardF7 },
            { KeyCode.F8, CorsairLedId.KeyboardF8 },
            { KeyCode.F9, CorsairLedId.KeyboardF9 },
            { KeyCode.F10, CorsairLedId.KeyboardF10 },
            { KeyCode.F11, CorsairLedId.KeyboardF11 },
            { KeyCode.F12, CorsairLedId.KeyboardF12 },
            { KeyCode.Insert, CorsairLedId.KeyboardInsert },
            { KeyCode.Home, CorsairLedId.KeyboardHome },
            { KeyCode.PageUp, CorsairLedId.KeyboardPageUp },
            { KeyCode.Delete, CorsairLedId.KeyboardDelete },
            { KeyCode.End, CorsairLedId.KeyboardEnd },
            { KeyCode.PageDown, CorsairLedId.KeyboardPageDown },
            { KeyCode.Numlock, CorsairLedId.KeyboardNumLock },
            { KeyCode.Keypad0, CorsairLedId.KeyboardKeypad0 },
            { KeyCode.Keypad1, CorsairLedId.KeyboardKeypad1 },
            { KeyCode.Keypad2, CorsairLedId.KeyboardKeypad2 },
            { KeyCode.Keypad3, CorsairLedId.KeyboardKeypad3 },
            { KeyCode.Keypad4, CorsairLedId.KeyboardKeypad4 },
            { KeyCode.Keypad5, CorsairLedId.KeyboardKeypad5 },
            { KeyCode.Keypad6, CorsairLedId.KeyboardKeypad6 },
            { KeyCode.Keypad7, CorsairLedId.KeyboardKeypad7 },
            { KeyCode.Keypad8, CorsairLedId.KeyboardKeypad8 },
            { KeyCode.Keypad9, CorsairLedId.KeyboardKeypad9 },
            { KeyCode.KeypadEnter, CorsairLedId.KeyboardEnter },
            { KeyCode.KeypadDivide, CorsairLedId.KeyboardKeypadSlash },
            { KeyCode.KeypadMultiply, CorsairLedId.KeyboardKeypadAsterisk },
            { KeyCode.KeypadMinus, CorsairLedId.KeyboardKeypadMinus },
            { KeyCode.KeypadPlus, CorsairLedId.KeyboardKeypadPlus },
            { KeyCode.KeypadPeriod, CorsairLedId.KeyboardKeypadPeriodAndDelete },
            { KeyCode.Semicolon, CorsairLedId.KeyboardSemicolonAndColon },
            { KeyCode.Equals, CorsairLedId.KeyboardEqualsAndPlus },
            { KeyCode.Comma, CorsairLedId.KeyboardCommaAndLessThan },
            { KeyCode.Minus, CorsairLedId.KeyboardMinusAndUnderscore },
            { KeyCode.Period, CorsairLedId.KeyboardPeriodAndBiggerThan },
            { KeyCode.Slash, CorsairLedId.KeyboardSlashAndQuestionMark },
            { KeyCode.LeftBracket, CorsairLedId.KeyboardBracketLeft },
            { KeyCode.Backslash, CorsairLedId.KeyboardBackslash },
            { KeyCode.RightBracket, CorsairLedId.KeyboardBracketRight },
            { KeyCode.Quote, CorsairLedId.KeyboardApostropheAndDoubleQuote }
        };
    }

    public static CorsairLedId GetKeyCodeLedIdMapping(KeyCode keyCode) {
        return keyCodeLedIdMapping.ContainsKey(keyCode) ? keyCodeLedIdMapping[keyCode] : CorsairLedId.Invalid;
    }
}
